// Encounter records from docs/experience-content-spec.md, sections 2–8.
// Plain data only. Image paths are site-relative (no leading slash); the
// display derivatives are generated by scripts/prepare-public.mjs.

const image = (name, height, alt, description) => ({
  originalPath: `images/evidence/${name}.png`,
  displayPath: `images/display/${name}-1280.jpg`,
  srcSet: [
    { path: `images/display/${name}-640.jpg`, width: 640 },
    { path: `images/display/${name}-1280.jpg`, width: 1280 },
  ],
  width: 1672,
  height,
  alt,
  description,
})

export const encounters = {
  letter: {
    id: 'letter',
    number: 'E1',
    title: 'A traveler at the threshold',
    kind: 'deep',
    image: image(
      'traveling-letter',
      941,
      'A traveler hands a sealed roll to a woman in a doorway.',
      "Two adults face each other at an entrance. The person on the left wears a worn-looking cloak and carries a bag. Both hold a rolled document tied with a red cord and seal. A lamp, jug, and interior courtyard are visible. The image does not reveal the document's contents or either person's identity.",
    ),
    situation: {
      label: 'Fictional situation',
      paragraphs: [
        'A newcomer brings a message recommending someone who needs accommodation. The household knows neither the messenger nor the person recommended. You are asked what kind of welcome to offer while the message is considered.',
      ],
    },
    observationPrompt: 'What do the hands, doorway, and sealed roll suggest? Separate what you see from what you assume.',
    decisionPrompt: 'What would you recommend, and what grounds for trust would you rely on?',
    feedbackLabel: 'Interpretation',
    choices: [
      {
        id: 'welcome',
        label: 'Offer hospitality immediately.',
        feedback: 'This meets a need without delay, while asking the household to act on a claim it has not checked.',
        followUp: 'What would make that responsibility reasonable?',
      },
      {
        id: 'temporary',
        label: 'Offer a temporary welcome while seeking information.',
        feedback: 'This combines welcome with inquiry, but someone must provide the time, space, and work that arrangement needs.',
        followUp: 'Whose work does your compromise require?',
      },
      {
        id: 'verify-first',
        label: 'Ask the traveler to wait while the message is checked.',
        feedback: 'This protects the household from an unverified claim, but delay itself can exclude someone who needs help.',
        followUp: 'How would the person waiting experience your decision?',
      },
      {
        id: 'another',
        label: 'Propose another approach or request information.',
        feedback: 'You can question the available options. Your alternative still needs to explain who acts and who waits.',
        followUp: 'What information would change your recommendation?',
      },
    ],
    neutralFeedback:
      'Welcoming and checking a claim can each impose costs. Before deciding, consider the needs of the visitor and the responsibilities of the host.',
    sourceIds: ['S3', 'S4'],
    sourceNote:
      'These are examples for comparison. They do not show that the pictured letter is a Pauline letter or that this Roman household followed the Didache.',
    reconsiderPrompt: 'I first relied on ___. After considering the sources and another perspective, I would ___. I still need to know ___.',
    imageLimitation:
      'The messenger, seal, clothing, and contents of the roll are reconstructed. No depicted person is an identified historical figure.',
  },

  meal: {
    id: 'meal',
    number: 'E2',
    title: 'A shared table, an uneven welcome',
    kind: 'deep',
    image: image(
      'shared-meal',
      940,
      'Three adults share bread around a low table with food and lamps.',
      'A woman on the left extends bread toward a bearded man at the center. An older woman sits on the right holding bread. A low round table holds more bread, bowls of food, a jug, and lamps. All three appear engaged with one another. No people outside this group are visible, and the image does not explain who prepared or supplied the food.',
    ),
    situation: {
      label: 'Fictional dialogue',
      paragraphs: [
        'A person preparing the table says: “Some who usually join us have not arrived. One of those here needs to leave soon. Shall we begin?”',
        'You have been asked for advice, not given authority over the gathering. Consider whose circumstances your recommendation includes.',
      ],
    },
    observationPrompt: 'What details suggest welcome? Who or what might be outside the frame? Record an observation and an assumption separately.',
    decisionPrompt: 'What would you recommend?',
    feedbackLabel: 'Fictional dialogue',
    choices: [
      {
        id: 'reserve',
        label: 'Begin and reserve food for those absent.',
        feedback: '“There will be food for them. Will they still share what happens around the table?”',
        followUp: 'Does receiving a portion equal participating?',
      },
      {
        id: 'wait',
        label: 'Wait for those who have not arrived.',
        feedback: '“Then the person who must leave may miss the meal.”',
        followUp: 'Who carries the burden of waiting?',
      },
      {
        id: 'separate',
        label: 'Serve food now; postpone the shared observance.',
        feedback: '“Would separating them change what we think we are doing?”',
        followUp: 'What have you assumed about meal and worship?',
      },
      {
        id: 'another',
        label: 'Propose another approach or request information.',
        feedback: '“What would you need to know before deciding?”',
        followUp: 'What happens while you seek that information?',
      },
    ],
    neutralFeedback:
      'A full table can suggest welcome while leaving absent people outside the frame. Consider what each arrangement makes possible and what it cannot provide.',
    sourceIds: ['S2', 'S1'],
    sourceNote: 'Neither source describes this household, these people, or this exact decision.',
    reconsiderPrompt:
      'Keep your recommendation, change it, or remain unsure. Explain how a source or another perspective affects your reasons. What cost remains?',
    transition: 'As you continue, notice who can influence how the gathering understands its shared practices.',
    imageLimitation:
      'The scene does not establish an exact Eucharistic ritual, seating arrangement, or relationship between a household meal and worship.',
  },

  reading: {
    id: 'reading',
    number: 'E3',
    title: 'Hearing together, interpreting differently',
    kind: 'brief',
    image: image(
      'scripture-reading',
      941,
      'One adult holds a large scroll while two others listen.',
      "A bearded adult at the center holds an open roll with marks resembling writing. A woman on the left and a man on the right face the reader. Food, a jug, and lamps sit nearby. The marks do not identify a readable historical passage; the picture does not establish anyone's office or literacy.",
    ),
    situation: {
      label: 'Fictional situation',
      paragraphs: [
        'After a reading, listeners disagree about what an obligation requires. One hears a command; another thinks the community must interpret what it means in practice. What would help them examine the disagreement?',
      ],
    },
    comparison: {
      label: 'Earlier comparison, not the text identified on this scroll',
      text: 'Paul urges the recipients to wait for one another when gathering to eat (1 Corinthians 11:33).',
      sourceId: 'S2',
    },
    decisionPrompt: 'What would you ask for first?',
    feedbackLabel: 'Interpretation',
    choices: [
      {
        id: 'repeat',
        label: 'Ask for the passage to be repeated.',
        feedback: 'Hearing the words again can correct a misunderstanding, but repetition may leave the disagreement about meaning intact.',
        followUp: 'What question should follow the repeated reading?',
      },
      {
        id: 'presider',
        label: 'Ask the presiding person to explain.',
        feedback: 'An explanation can guide the group; authority alone does not show why an interpretation fits the text.',
        followUp: 'What reasons would you ask the speaker to provide?',
      },
      {
        id: 'listeners',
        label: 'Ask the listeners to explain what they heard.',
        feedback: 'Different accounts can expose assumptions, although agreement among speakers would not by itself settle the meaning.',
        followUp: 'How would you compare their interpretations with the text?',
      },
    ],
    neutralFeedback:
      'A text, its reader, and its interpretation are related but distinct. Think about what kind of explanation would help you judge the meaning.',
    sourceIds: ['S1', 'S2'],
    sourceNote: 'Each source keeps its own setting; neither identifies what this household read.',
    notePrompt: 'I would ask ___. The answer could help me distinguish ___ from ___.',
    imageLimitation:
      "The roll's script and contents are not identified. Do not infer a universal literacy rate, gender rule, or scroll-versus-book practice from this scene.",
  },

  diversity: {
    id: 'diversity',
    number: 'E4',
    title: 'Who can speak in this circle?',
    kind: 'brief',
    image: image(
      'social-diversity',
      941,
      'Four adults in different clothing sit in conversation around a low table.',
      'Two women sit on the left and two men to the right. One woman wears a richly colored garment and jewelry; another person wears an apron-like garment. They appear to take part in one conversation. Clothing differences are visible, but the image cannot establish legal status, occupation, wealth, or influence.',
    ),
    situation: {
      label: 'Fictional situation',
      paragraphs: [
        'In this fictional scenario, a person who provides the meeting space speaks at length. Another participant hesitates to disagree. These relationships are supplied by the scenario, not established by the costumes.',
      ],
    },
    decisionPrompt: 'What would you do first?',
    feedbackLabel: 'Interpretation',
    choices: [
      {
        id: 'clarify',
        label: 'Ask the provider of the space to clarify.',
        feedback: 'This may make the position easier to examine while leaving the conversation centered on the same speaker.',
        followUp: 'How would you make room for another account?',
      },
      {
        id: 'public',
        label: 'Invite the hesitant participant to speak.',
        feedback: 'A public invitation can open the conversation, but it may also expose someone who does not feel free to disagree.',
        followUp: 'What makes an invitation safe or unsafe in this situation?',
      },
      {
        id: 'private',
        label: 'Offer a private way to contribute.',
        feedback: 'A private conversation may reduce exposure without changing what the wider group hears.',
        followUp: 'How could the concern be considered without taking control of its speaker?',
      },
      {
        id: 'question-premise',
        label: 'Question what the scenario assumes.',
        feedback: 'Hesitation can have different explanations. It need not mean agreement, fear, or lack of knowledge.',
        followUp: 'What would you need to know before describing the relationship?',
      },
    ],
    neutralFeedback:
      'Sitting together does not reveal how freely each person can speak. Ask what the image shows and what the scenario asks you to imagine.',
    perspective: {
      label: 'Fictional dialogue',
      text: '“You have invited me to speak. I also depend on the person whose proposal you want me to question.”',
      note: 'This illustrates one possible tension; it does not reveal a secret factual identity in the picture.',
    },
    sourceIds: ['S2', 'S3'],
    sourceNote: 'These are comparisons from earlier, different communities.',
    notePrompt: 'I inferred ___ from appearance or position. What I actually observed was ___.',
    recall: {
      encounterId: 'meal',
      heading: 'Earlier, at the table…',
      question: 'Does this conversation complicate your earlier view of participation?',
    },
    imageLimitation:
      'These are fictional people. Do not label any figure as enslaved, freed, a worker, or a host solely from appearance.',
  },

  care: {
    id: 'care',
    number: 'E5',
    title: 'Care when needs do not match resources',
    kind: 'deep',
    image: image(
      'care-for-others',
      941,
      'Food, coins, and a folded textile lie between two adults.',
      'An adult on the left holds bread over a basket containing food. A folded textile is held between that person and an older adult on the right. Coins are visible in a dish below. The still image does not establish ownership of the goods, the direction of every transfer, or the wishes of a recipient.',
    ),
    situation: {
      label: 'Fictional situation',
      paragraphs: [
        'A traveler needs help to continue a journey. A local household needs ongoing support. In this fictional situation, the available help cannot fully meet both requests today. Before recommending an arrangement, consider whose needs you understand and whose voice you have not heard.',
      ],
    },
    observationPrompt: 'What resources are visible? What information about the people and their needs is missing?',
    decisionPrompt: 'What would you recommend?',
    feedbackLabel: 'Interpretation',
    choices: [
      {
        id: 'immediate',
        label: 'Address the most immediate need first.',
        feedback: 'Urgency gives a reason to act now, but the recurring need remains and may grow harder to meet.',
        followUp: 'How did you decide which need was most urgent?',
      },
      {
        id: 'divide',
        label: 'Divide the help between both requests.',
        feedback: 'Sharing can acknowledge both requests while leaving each insufficiently met.',
        followUp: 'What would each person say your share makes possible?',
      },
      {
        id: 'seek-help',
        label: 'Seek another contributor before deciding.',
        feedback: 'More help may improve the options, but asking takes time and could attach further expectations to the support.',
        followUp: 'Who bears the cost of delay or a new obligation?',
      },
      {
        id: 'another',
        label: 'Ask another question or propose an alternative.',
        feedback: 'An alternative should explain the information it needs and how people seeking help participate in the decision.',
        followUp: 'Whose account would you hear next?',
      },
    ],
    neutralFeedback:
      'Visible generosity does not tell you how a decision was made. Consider needs, available help, and the participation of those affected.',
    perspective: {
      label: 'Fictional dialogue',
      text: '“Before deciding for me, ask what would help me most.”',
    },
    sourceIds: ['S1'],
    sourceNote: 'Justin describes organized assistance. His account does not show that aid alone explains conversion, numerical growth, or moral superiority.',
    reconsiderPrompt: 'My proposal benefits ___. It leaves ___ unresolved. After hearing another perspective, I would ___.',
    recall: {
      encounterId: 'letter',
      heading: 'Earlier, at the threshold…',
      question: 'Does your standard for welcome affect this recommendation?',
    },
    imageLimitation:
      'The picture illustrates material support, but does not establish who gives, who decides, or how the exchange is experienced.',
  },

  pressure: {
    id: 'pressure',
    number: 'E6',
    title: 'Looking back from the threshold',
    kind: 'brief',
    image: image(
      'roman-pressure',
      941,
      'A household shrine with a statue and smoking vessel stands in the foreground; people sit farther back.',
      'An architectural niche contains a small standing statue. Lamps and vessels surround it, including a vessel emitting smoke. Beyond a column, several people sit together in a room. No one is shown performing a rite at the shrine or making an accusation. Their relationship to the shrine is not established.',
    ),
    situation: {
      label: 'Interpretive task',
      paragraphs: [
        'You are choosing a caption for this reconstruction. Which statement is best supported by what is actually depicted? Then compare the image with a historical account from a different setting.',
      ],
    },
    decisionPrompt: 'Which caption is best supported by the image?',
    feedbackLabel: 'Interpretation',
    choices: [
      {
        id: 'raid',
        label: 'This proves a raid is imminent.',
        feedback: 'No raid, accusation, or official appears in this image. Fear of an imminent raid is not established by its contents.',
        followUp: "What further evidence would let you make a claim about these people's actions?",
        support: 'unsupported',
      },
      {
        id: 'context',
        label: "It depicts religious surroundings, but cannot establish the group's actions.",
        feedback: 'This distinguishes the shrine that is depicted from claims about the people behind it. Their relationship requires further evidence.',
        followUp: "What further evidence would let you make a claim about these people's actions?",
        support: 'supported',
      },
      {
        id: 'shared-rites',
        label: 'This proves everyone shown participated in the same rites.',
        feedback: 'Sharing a frame does not prove shared practice. The smoking vessel also does not establish which person, if any, used it.',
        followUp: "What further evidence would let you make a claim about these people's actions?",
        support: 'unsupported',
      },
    ],
    neutralFeedback:
      'Describe the depicted shrine and gathering separately before inferring how they relate. A dramatic atmosphere does not supply missing evidence.',
    sourceIds: ['S5'],
    sourceNote:
      'This administrative exchange comes from an earlier time and a different province. It is not a report about the pictured gathering.',
    notePrompt: 'I can describe ___. I cannot conclude ___. Evidence I would need is ___.',
    imageLimitation:
      'The image does not prove an active shrine in a Christian-owned household, a group’s refusal of a rite, or a constant threat of persecution.',
  },
}

export const supportLabels = {
  supported: 'Supported by what is depicted',
  unsupported: 'Not supported by what is depicted — a revisable interpretation',
}
